openapi: 3.0.0
info:
  title: Anonymizer API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://0.0.0.0:8000/api
paths:
  /categories:
    get:
      summary: Returns a category collection.
      responses:
        '200':
          description: A JSON array of categories
          content:
           application/json:
              schema:
                $ref: '#/components/schemas/Categories'            
        '404':
          $ref: '#/components/responses/NotFound'
components:
  schemas:
    Category:     
      type: object
      properties:
        id:
          type: integer
          example: 2
        name:
          type: string
          example: "CategoryName"
        category_id: 
          type: integer
          example: 1
        is_parent: 
          type: boolean
          example: true
        status: 
          type: string
          example: PROCESSED
        published: 
          type: boolean
          example: true
        order: 
          type: integer
          example: 102
    Categories: 
      type: array
      items: 
        $ref: '#/components/schemas/Category'
  responses:
    NotFound:
      description: Entity not found

